# Name: Andrew Kennedy
# UF ID: 15618865
# Discussion: 1085

hw4prob1: hw4prob1.o
	g++ -Wall -ggdb hw4prob1.o -o hw4prob1

hw4prob1.o: hw4prob1.cpp linkedBinaryTree.h
	g++ -Wall -ggdb -c hw4prob1.cpp

hw4prob2: hw4prob2.o
	g++ -Wall -ggdb hw4prob2.o -o hw4prob2

hw4prob2.o: hw4prob2.cpp binarySearchTree.h
	g++ -Wall -ggdb -c hw4prob2.cpp

hw4prob3: hw4prob3.o
	g++ -Wall -ggdb hw4prob3.o -o hw4prob3

hw4prob3.o: hw4prob3.cpp
	g++ -Wall -ggdb -c hw4prob3.cpp
